sudo: required
language: generic
services: 
   - docker 

before_install:
   - docker build -t yesha123/docker-react -f Dockerfile.dev .

script:
   - docker run -e CI=true yesha123/docker-react npm run test 
